meta:
  pk: id
  fields:
    id: INT NOT NULL AUTO_INCREMENT
    uri: VARCHAR(512)
    copyright: VARCHAR(1024)
    description: VARCHAR(1024)
    keywords: VARCHAR(1024)
  form:
    fields:
      copyright:
        widget: textarea
        widget_conf:
          required: 0
      description:
        widget: textarea
        widget_conf:
          required: 0
      keywords:
        widget: textarea
        widget_conf:
          required: 0
    names:
      en: Meta tag
      zh: Meta tag