mail:
  # conf for email sending to amdin
  admin:
    to: info@ct21.com.au
    bcc: jeffreycaizhenyuan@gmail.com
    cc: george@ct21.com.au
    from: george@ct21.com.au
    mailer: smtp
    SMTPSecure: tls
    host: smtp.gmail.com
    port: 587
    username: 3dUV==Abnl1Qt92YuwWah12ZAlXZuRWez5WalZ3bsRmbpZmU
    nickname: ct21 website
    password: C9GT==AUwBHThJjMxIzNxAjW

